name: Compile docs

env:
  PYTHON_VERSION: 3.11
  GCC_MAJOR_VERSION: 12
  CONAN_REQUEST_TIMEOUT: 300

on:
  workflow_dispatch:


jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
          fail-fast: false
          matrix:
              # tag: [1_4_1, 1_4_0, 1_3_0, 1_2_0, 1_1_1, 1_1_0, 1_0_8, 1_0_7, 1_0_5, 1_0_3]
              tag: [1_3_0]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Install GCC ${{ env.GCC_MAJOR_VERSION }}
          run: sudo apt install gcc-${{ env.GCC_MAJOR_VERSION }} g++-${{ env.GCC_MAJOR_VERSION }}

        - name: Clone discopygal
          run: git clone --branch discopygal_${{ matrix.tag }} --depth 1 https://${{ secrets.MY_GITHUB_PAT }}@github.com/TAU-CGL/discopygal.git

        - name: Preparing requirements
          run: |
                pipenv lock --clear
                pip install pipenv
                sed -i '/pyqt5designer = "*"/d' Pipfile # Remove bad dependency for linux
                CC=gcc-${{ env.GCC_MAJOR_VERSION }} CXX=g++-${{ env.GCC_MAJOR_VERSION }} pipenv install --python $(which python) --dev --verbose
                sudo apt install texlive-latex-extra dvipng
          working-directory: ./discopygal

        # - name: Install Revolving Areas
        #   run: pipenv run pip install ../ra-1.0.0-cp311-cp311-linux_x86_64.whl
        #   working-directory: ./discopygal

        - name: Set updated template
          run: |
                rm -rf discopygal/docs/_templates
                mkdir discopygal/docs/_templates
                cp docs_layout.html discopygal/docs/_templates/layout.html
                echo "autodoc_mock_imports = [\"RA\"]" >> discopygal/docs/conf.py

        - name: Build docs
          run: |
                pipenv run make clean
                pipenv run make html
          working-directory: ./discopygal/docs

        - name: Upload docs
          uses: actions/upload-artifact@v4
          with:
            path: discopygal/docs/_build/html
            name: html_docs_${{ matrix.tag }}

