name: Run Experiment

on:
    workflow_dispatch:  # Manual trigger only
        # inputs:
        #     commit_sha:
        #         description: 'Commit SHA to run the experiment'
        #         required: true
        #         default: 'main'

jobs:
    run-python-script:
        runs-on: ubuntu-latest

        continue-on-error: true

        strategy:
            matrix:
              chunk: [0, 1, 2000]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            #   with:
            #     ref: ${{ github.event.inputs.commit_sha }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.9'

            - name: Cache Python packages
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}
                  restore-keys: |
                    ${{ runner.os }}-pip-

            - name: Install Discopygal
              run: |
                python -m pip install --upgrade pip
                pip install -v discopygal_taucgl-1.2.0-py3-none-any.whl

            - name: Run Experiment Script
              run: python experiment_drrt_star.py ${{ matrix.chunk }} ${{ matrix. }}

            - name: Upload CSV Files as Artifact
              uses: actions/upload-artifact@v3
              with:
                name: results
                path: ./results_drrt_star
                retention-days: 7  # Keep artifacts for 7 days
