name: Run Experiment

on:
    workflow_dispatch:  # Manual trigger only
        inputs:
            experiment_config:
                description: 'Configuration file of experiment to run'
                required: true
                default: 'exp_drrt_star/exp_config.json'
        #     commit_sha:
        #         description: 'Commit SHA to run the experiment'
        #         required: true
        #         default: 'main'

jobs:
    startup-config:
      runs-on: ubuntu-latest

      outputs:
          chunks: ${{ steps.get-config.outputs.chunks }}
          scenarios_file: ${{ steps.get-config.outputs.scenarios_file }}
          chunks_amount: ${{ steps.get-config.outputs.chunks_amount }}
          python_version: ${{ steps.get-config.outputs.python_version }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Read JSON Config
          id: get-config
          run: |
               config_file=${{ github.event.inputs.experiment_config }}
               chunks=$(jq -c '.chunks' $config_file)
               scenarios_file=$(jq -r '.scenarios_file' $config_file)
               chunks_amount=$(jq -r '.chunks_amount' $config_file)

               {
                echo "chunks=$chunks";
                echo "scenarios_file=$scenarios_file";
                echo "chunks_amount=$chunks_amount";
                echo "python_version=3.11.9";           # Python version
               } >> $GITHUB_OUTPUT

               echo "scenarios_file: $scenarios_file"
               echo "chunks: $chunks"
               echo "chunks_amount: $chunks_amount"
               echo "python_version: $python_version"

    run-experiment-chunk:
        runs-on: ubuntu-latest
        needs: startup-config

        continue-on-error: true

        strategy:
            matrix:
              chunk: ${{ fromJson(needs.startup-config.outputs.chunks) }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ needs.startup-config.outputs.python_version }}

            - name: Cache Python packages
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

            - name: Install Discopygal
              run: pip install -v *.whl

            - name: Run Experiment Script
              run: scenarios_runner results ${{ needs.startup-config.outputs.scenarios_file }} ${{ needs.startup-config.outputs.chunks_amount }} ${{ matrix.chunk }}

            - name: Upload CSV Files as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: results_chunk_${{ matrix.chunk }}
                path: ./results
                retention-days: 7  # Keep artifacts for 7 days

    sum_results:
        runs-on: ubuntu-latest
        needs: [startup-config, run-experiment-chunk]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ needs.startup-config.outputs.python_version }}

            - name: Cache Python packages
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

            - name: Install Discopygal
              run: pip install -v *.whl

            - name: Download Results
              uses: actions/download-artifact@v4
              with:
                  name: results
                  path: ./results

            - name: Process results
              run: scenarios_runner results ${{ needs.startup-config.outputs.scenarios_file }} ${{ needs.startup-config.outputs.chunks_amount }} end

            - name: Re-upload Updated Results
              uses: actions/upload-artifact@v4
              with:
                  name: results
                  path: ./results
                  retention-days: 7  # Keep artifacts for 7 days
