name: Run Frechet comparison

env:
  PYTHON_VERSION: 3.12
  GCC_MAJOR_VERSION: 12
  MAX_JOBS: 256 # Max amount of jobs is 256

on:
    workflow_dispatch:  # Manual trigger only

jobs:
    startup:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Install GCC ${{ env.GCC_MAJOR_VERSION }}
          run:  |
                 sudo apt install gcc-${{ env.GCC_MAJOR_VERSION }} g++-${{ env.GCC_MAJOR_VERSION }}
                 echo "CC=gcc-${{ env.GCC_MAJOR_VERSION }}" >> $GITHUB_ENV
                 echo "CXX=g++-${{ env.GCC_MAJOR_VERSION }}" >> $GITHUB_ENV

        - name: Cache Python packages
          uses: actions/cache@v4
          with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/discopygal*.whl') }}

        - name: Install Discopygal
          run: pip install -v discopygal*.whl


    run-experiment:
      runs-on: ubuntu-latest
      needs: startup

      strategy:
          fail-fast: false
          matrix:
              scene: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Cache Python packages
          uses: actions/cache@v4
          with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/discopygal*.whl') }}

        - name: Install GCC ${{ env.GCC_MAJOR_VERSION }}
          run:  |
                 sudo apt install gcc-${{ env.GCC_MAJOR_VERSION }} g++-${{ env.GCC_MAJOR_VERSION }}
                 echo "CC=gcc-${{ env.GCC_MAJOR_VERSION }}" >> $GITHUB_ENV
                 echo "CXX=g++-${{ env.GCC_MAJOR_VERSION }}" >> $GITHUB_ENV

        - name: Install Discopygal
          run: |
                  pip install -v discopygal*.whl
                  pip install frechetlib

        - name: Build Bringmann frechet
          run: |
                chmod +x bringmann_calc_frechet_distance

        - name: Run Experiment Script
          run: python frechet_distance/compare_frechets.py ${{ matrix.scene }}

        - name: Upload CSV Files as Artifact
          uses: actions/upload-artifact@v4
          with:
            path: ./frechet_comparison.csv
