name: Run Experiment

on:
    workflow_dispatch:  # Manual trigger only
        # inputs:
        #     commit_sha:
        #         description: 'Commit SHA to run the experiment'
        #         required: true
        #         default: 'main'

jobs:
    startup-config:
      runs-on: ubuntu-latest
      outputs:
          chunks: ${{ steps.get-config.outputs.chunks }}
          scenarios_file: ${{ steps.get-config.outputs.scenarios_file }}
          chunks_amount: ${{ steps.get-config.outputs.chunks_amount }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Read JSON Config
          id: get-config
          run: |
               config_file=exp_drrt_star.json
               chunks=$(jq -c '.chunks' $config_file)
               scenarios_file=$(jq -r '.scenarios_file' $config_file)
               chunks_amount=$(jq -r '.chunks_amount' $config_file)

               echo "{chunks}={$chunks}" >> $GITHUB_OUTPUT
               echo "{scenarios_file}={$scenarios_file}" >> $GITHUB_OUTPUT
               echo "{chunks_amount}={$chunks_amount}" >> $GITHUB_OUTPUT

               echo "scenarios_file: $scenarios_file"
               echo "chunks: $chunks"
               echo "chunks_amount: $chunks_amount"

    run-experiment-chunk:
        runs-on: ubuntu-latest
        needs: startup-config

        continue-on-error: true

        strategy:
            matrix:
              chunk: ${{ needs.startup-config.outputs.chunks }}
              # chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            #   with:
            #     ref: ${{ github.event.inputs.commit_sha }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.9'

            - name: Cache Python packages
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

            - name: Install Discopygal
              run: |
                python -m pip install --upgrade pip
                pip install -v discopygal_taucgl-1.2.0-py3-none-any.whl

            - name: Run Experiment Script
              run: python run_experiment.py ${{ needs.startup-config.outputs.scenarios_file }} ${{ matrix.chunk }} ${{ needs.startup-config.outputs.chunks_amount }}

            - name: Upload CSV Files as Artifact
              uses: actions/upload-artifact@v3
              with:
                name: results
                path: ./results
                retention-days: 7  # Keep artifacts for 7 days

    sum_results:
        runs-on: ubuntu-latest
        needs: run-experiment-chunk

        steps:
          - name: Download Results
            uses: actions/download-artifact@v3

          - name: Process results
            run: python run_experiment.py end

          - name: Re-upload Updated Results
            uses: actions/upload-artifact@v3
            with:
                name: results
                path: ./results
                retention-days: 7  # Keep artifacts for 7 days
