name: Run Multi-robot Frechet comparison

env:
  PYTHON_VERSION: 3.11.9
  MAX_JOBS: 256 # Max amount of jobs is 256

on:
    workflow_dispatch:  # Manual trigger only

jobs:
    run-experiment:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          num: [6,7,8,9,10]
          # num: [2,3,4,5,6,7,8,9,10]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Cache Python packages
          uses: actions/cache@v4
          with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

        - name: Install Discopygal
          run: |
              pip install -v *.whl
              pip install frechetlib

        - name: Run Experiment Script
          run: python frechet_distance/multi_robot_frechets.py ${{ matrix.num }}

        - name: Upload CSV Files as Artifact
          uses: actions/upload-artifact@v4
          with:
            name: results_num_${{ matrix.num }}
            path: ./frechet_comparison.csv
