name: Run Experiment

env:
  PYTHON_VERSION: 3.11.9
  MAX_JOBS: 256 # Max amount of jobs is 256

on:
    workflow_dispatch:  # Manual trigger only

jobs:
    run-experiment:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Cache Python packages
          uses: actions/cache@v4
          with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

        - name: Install Discopygal
          run: |
                  pip install -v *.whl
                  pip install frechetlib

        - name: Run Experiment Script
          run: python compare_frechets.py

        - name: Upload CSV Files as Artifact
          uses: actions/upload-artifact@v4
          with:
            path: ./frechet_comparison.csv
