name: Run Experiment

on:
    workflow_dispatch:  # Manual trigger only
        # inputs:
        #     commit_sha:
        #         description: 'Commit SHA to run the experiment'
        #         required: true
        #         default: 'main'

jobs:
    config-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Read config from json
              run: |
                CONFIG_FILE=exp_drrt_star.json
                scenarios_file=$(jq -r '.scenarios_file' $CONFIG_FILE)
                chunks=$(jq -r '.chunks' $CONFIG_FILE)
                chunks_amount=$(jq -r '.chunks_amount' $CONFIG_FILE)

                echo "SCENARIOS_FILE=$scenarios_file" >> $GITHUB_ENV
                echo "CHUNKS=$chunks" >> $GITHUB_ENV
                echo "CHUNKS_AMOUNT=$CHUNKS_AMOUNT" >> $GITHUB_ENV

                echo "SCENARIOS_FILE: $SCENARIOS_FILE"
                echo "CHUNKS: $CHUNKS"
                echo "CHUNKS_AMOUNT: $CHUNKS_AMOUNT"


    run-experiment-chunk:
        runs-on: ubuntu-latest

        continue-on-error: true

        strategy:
            matrix:
              chunk: $CHUNKS
              # chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            #   with:
            #     ref: ${{ github.event.inputs.commit_sha }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.9'

            - name: Cache Python packages
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

            - name: Install Discopygal
              run: |
                python -m pip install --upgrade pip
                pip install -v discopygal_taucgl-1.2.0-py3-none-any.whl

            - name: Run Experiment Script
              run: python run_experiment.py $SCENARIOS_FILE ${{ matrix.chunk }} $CHUNKS_AMOUNT

            - name: Upload CSV Files as Artifact
              uses: actions/upload-artifact@v3
              with:
                name: results
                path: ./results
                retention-days: 7  # Keep artifacts for 7 days

    sum_results:
        runs-on: ubuntu-latest
        needs: run-experiment-chunk

        steps:
          - name: Download Results
            uses: actions/download-artifact@v3

          - name: Process results
            run: python run_experiment.py end

          - name: Re-upload Updated Results
            uses: actions/upload-artifact@v3
            with:
                name: results
                path: ./results
                retention-days: 7  # Keep artifacts for 7 days
