name: Check version release

env:
  PYTHON_VERSION: 3.11.9

on:
  workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Clone discopygal
          run: git clone git@github.com:TAU-CGL/discopygal.git

        - name: Build package
          run: python sc

    check:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # os: [ubuntu-latest, windows-latest, macos-latest]
                os: [ubuntu-latest]
                # python-version: ["3.9", "3.10", "3.11"]
                python-version: ["3.10"]

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install test dependencies
          run: |
                pip install --upgrade pip setuptools wheel scikit-build-core
                pip install pytest pyautogui networkx


        - name: Set compiler variables (macOS)
          if: runner.os == 'macOS'
          run: |
                echo "Setting compiler env vars"
                echo "CC=clang" >> $GITHUB_ENV
                echo "CXX=clang++" >> $GITHUB_ENV

        - name: Install Discopygal
          if: runner.os != 'Windows'
          run: pip install -v *.whl

        - name: Install Discopygal (Windows)
          if: runner.os == 'Windows'
          run: |
                Get-ChildItem -Filter *.whl | ForEach-Object {
                    pip install -v $_.FullName
                }

        - name: Run tests
          if: runner.os != 'Windows'
          run: xvfb-run -a pytest -v ./tests

        - name: Run tests (Windows)
          if: runner.os == 'Windows'
          run: pytest -v ./tests

