name: "Set Discopygal environment"

runs:
    using: "composite"
    steps:
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.9'

        - name: Cache Python packages
          uses: actions/cache@v3
          with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/*.whl') }}

        - name: Install Discopygal
          run: pip install -v *.whl
